//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 11:24:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:9090/demoServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._9090.demoservices;
